### ISSUE TITLE
Learn Docker

### ISSUE THREAD

**Issue by jekram** [Cloudkibo/ice#13]
Learn Docker _ I will update you about this. 

Doctor is an alternate to Virtual Machine.

Learn enough to we can use docker to deploy.

WWW.docker.com

This is not urgent - Just learn on how to be a user of Docker.

We would need this by end of the month.

**Comment by sojharo** [comment]
I just saw a quick tutorial of Docker from following lnk. Need to read more on it.

https://www.docker.com/tryit

It talks about distributed applications. Does it mean that our application should be based on microservices architecture to deploy it on docker?

**Comment by jekram** [comment]
Container / Docker gives you that option of running microservices. Docker does not force you into an architecture. 

The way to think about it is to start always with a large monolithic application. As code becomes complex to maintain then you break up the code into individual services. Microservices can be docker or non docker.

**Comment by sojharo** [comment]
I read more about it today and also looked into the user manual.

Next on this, I would make an account and try to upload a sample application too.

**Comment by jekram** [comment]
Sojharo 

I just read these 6-7 pages of Docker document , please review it.

http://docs.docker.com/userguide

Allah Hafiz

Jawaid
