### ISSUE TITLE
Enhance Support Process

### ISSUE THREAD

**Issue by jekram** [Cloudkibo/ice#17]
Enhance Support Process 

Objective:

To run a SaaS we need to provide a very high quality service., and when service fails (bugs) we need to provide exceptional customer service.

We need to improve the current support process to be more responsive to customers.

The purpose of this document is to agree on:
1.	Support Process 
2.	SLA. 

Support Process:

1.	An Engineer will be assigned on a weekly basis whose primary job will be to monitor the support queue and respond to the customer issues. 

2.	Customer Support:  Within 1 business day the support engineer needs to either resolve the issue or escalate it to Engineering. 

a.	Resolution:  For the issue to be resolved one of the following needs to happen:
i.	The support Engineer resolves the customer issue and informs the customer the issue has been resolved. 
ii.	The support Engineer determines that the system is working as per design and he informs the customer and mark the issue as resolved.
iii.	The support Engineer determines the customer is asking for an enhancement. In that case the customer is informed this is an enhancement request and the enhancement request has been sent to engineering for review. 

b.	Escalation: The support engineer determines that this is a bug in the system and he cannot resolve it. The support Engineer opens an issue in PM and informs the customer a Bug has been opened for his issue.

c.	Priority: Paid customer issues would he given higher priority over free customers.

3.	Engineering Escalation:
a.	On a daily basis the customers issues would be triaged by Engineering Management.
b.	All customer issues escalated to Engineering would have a SLA of two business days. Within 2 business days either the issues is resolved or a high level ETA is provided to the customer on when the issue will be resolved.
c.	Non Resolution:
i.	If an issue cannot be resolved within 2 business days then the customers is provided an high level date of resolution.

SLA:

At this stage these SLA are internal only. These SLA’s would not be communicated to customers yet.

Once we have internal SLA tracking and measurement in place we would communicate SLA to customer

1.	Goal of SLA’s: 
a.	For the first three months the target SLA’s are:
i.	50% of the issues are resolved within 1 business day or has been escalate to Engineering.
ii.	50% of the Engineering bugs are resolved with 2 business days of escalation.
b.	After three months we would readjust the SLA targets.

Reporting and Monitoring: 

1.	Report on internal SLA on a weekly basis (Jawaid)
2.	We will review on how the support process is working on a monthly basis and fine tune as required  (Jawaid)

 
Next Step:

1.	Agreement on the framework and SLA  
2.	Publish process on PM (Lekha)
3.	Avi / Manisha to communicate to Eng.
4.	Phase 2 implementations 
a.	Slack integration 
b.	Establish Customer SLA

**Comment by jekram** [comment]
Enhance Support Process 


Objective:

To run a SaaS we need to provide a very high quality service., and when service fails (bugs) we need to provide exceptional customer service.

We need to improve the current support process to be more responsive to customers.

The purpose of this document is to agree on:
1.	Support Process 
2.	SLA. 


Support Process:

1.	An Engineer will be assigned on a weekly basis whose primary job will be to monitor the support queue and respond to the customer issues. 

2.	Customer Support:  Within 1 business day the support engineer needs to either resolve the issue or escalate it to Engineering. 

     a.	Resolution:  For the issue to be resolved one of the following needs to happen:
              i.	The support Engineer resolves the customer issue and informs the customer the issue has been resolved. 
             ii.	The support Engineer determines that the system is working as per design and he informs the customer and mark the issue as resolved.
            iii.	The support Engineer determines the customer is asking for an enhancement. In that case the customer is informed this is an enhancement request and the enhancement request has been sent to engineering for review. 

      b.	Escalation: The support engineer determines that this is a bug in the system and he cannot resolve it. The support Engineer opens an issue in PM and informs the customer a Bug has been opened for his issue.

     c.	Priority: Paid customer issues would he given higher priority over free customers.


3.	Engineering Escalation:
     a.	On a daily basis the customers issues would be triaged by Engineering Management.
     b.	All customer issues escalated to Engineering would have a SLA of two business days. Within 2 business days either the issues is resolved or a high level ETA is provided to the customer on when the issue will be resolved.
     c.	Non Resolution:
              i.	If an issue cannot be resolved within 2 business days then the customers is provided an high level date of resolution.

SLA:

At this stage these SLA are internal only. These SLA’s would not be communicated to customers yet.

Once we have internal SLA tracking and measurement in place we would communicate SLA to customer


1.	Goal of SLA’s: 
     a.	For the first three months the target SLA’s are:
              i.	50% of the issues are resolved within 1 business day or has been escalate to Engineering.
             ii.	50% of the Engineering bugs are resolved with 2 business days of escalation.
     b.	After three months we would readjust the SLA targets.


Reporting and Monitoring: 

1.	Report on internal SLA on a weekly basis (Jawaid)
2.	We will review on how the support process is working on a monthly basis and fine tune as required  (Jawaid)

 
Next Step:

1.	Agreement on the framework and SLA  
2.	Publish process on PM (Lekha)
3.	Avi / Manisha to communicate to Eng.
4.	Phase 2 implementations 
     a.	Slack integration 
     b.	Establish Customer SLA

**Comment by jekram** [comment]
Enhance Support Process 


Objective:

To run a SaaS we need to provide a very high quality service., and when service fails (bugs) we need to provide exceptional customer service.

We need to improve the current support process to be more responsive to customers.

The purpose of this document is to agree on:
1.	Support Process 
2.	SLA. 


Support Process:

1.	An Engineer will be assigned on a weekly basis whose primary job will be to monitor the support queue and respond to the customer issues. 

2.	Customer Support:  Within 1 business day the support engineer needs to either resolve the issue or escalate it to Engineering. 

a.	Resolution:  For the issue to be resolved one of the following needs to happen:
i.	The support Engineer resolves the customer issue and informs the customer the issue has been resolved. 
ii.	The support Engineer determines that the system is working as per design and he informs the customer and mark the issue as resolved.
iii.	The support Engineer determines the customer is asking for an enhancement. In that case the customer is informed this is an enhancement request and the enhancement request has been sent to engineering for review. 

b.	Escalation: The support engineer determines that this is a bug in the system and he cannot resolve it. The support Engineer opens an issue in PM and informs the customer a Bug has been opened for his issue.

c.	Priority: Paid customer issues would he given higher priority over free customers.


3.	Engineering Escalation:
a.	On a daily basis the customers issues would be triaged by Engineering Management.
b.	All customer issues escalated to Engineering would have a SLA of two business days. Within 2 business days either the issues is resolved or a high level ETA is provided to the customer on when the issue will be resolved.
c.	Non Resolution:
i.	If an issue cannot be resolved within 2 business days then the customers is provided an high level date of resolution.

SLA:

At this stage these SLA are internal only. These SLA’s would not be communicated to customers yet.

Once we have internal SLA tracking and measurement in place we would communicate SLA to customer


1.	Goal of SLA’s: 
a.	For the first three months the target SLA’s are:
i.	50% of the issues are resolved within 1 business day or has been escalate to Engineering.
ii.	50% of the Engineering bugs are resolved with 2 business days of escalation.
b.	After three months we would readjust the SLA targets.


Reporting and Monitoring: 

1.	Report on internal SLA on a weekly basis (Jawaid)
2.	We will review on how the support process is working on a monthly basis and fine tune as required  (Jawaid)

 
Next Step:

1.	Agreement on the framework and SLA  
2.	Publish process on PM (Lekha)
3.	Avi / Manisha to communicate to Eng.
4.	Phase 2 implementations 
a.	Slack integration 
b.	Establish Customer SLA

**Comment by sojharo** [comment]
Salaam,

This is to inform that It seems these issues are mistakenly opened here.

**Comment by jekram** [comment]
Sojharo asak

Yes. Please ignore
