### ISSUE TITLE
Researched on Github 

### ISSUE THREAD

**Issue by jekram** [Cloudkibo/ice#2]
Researched on Github

Post links and finding here

**Comment by sojharo** [comment]
. Obtain developer license to integrate with Github Enterprise
. can set controls for employees and contractors
. can set the access level
. I have asked the question on their support page about what exact information we want to retrieve as developer
. user management
. we can set the access levels on repositories for team members
. read only level, LDAP Group management
. Please post the link
. Jawaid to get developer account

. Analytics are given
. these all were features of github enterprise
. github enterprise is separate than making an organization on github
. for enterprise, we need to obtain the developer license
. they did not talk about billing, i have asked question from them on support regarding this
. admin can promote, demote any user’s role
. admin can suspend or unsuspend a user

. In organizations, we can do many things with memberships, adding, removing members
. we can have teams in organizations, we can do many things with teams too

**Comment by sojharo** [comment]
Informtion about libraries which are given by Github.

https://developer.github.com/libraries/

Documentation on API

https://developer.github.com/v3/

Development Guide

https://developer.github.com/guides/

And Developer Home Page

https://developer.github.com/

**Comment by jekram** [comment]
Thanks. I will review and get back
