### ISSUE TITLE
Research on Azure API

### ISSUE THREAD

**Issue by jekram** [Cloudkibo/ice#6]
Research on Azure billing API

Post link and finding here.

**Comment by sojharo** [comment]
Azure looked same as AWS in may ways. Both had policies, groups, identity and access management and usage information. One similar thing in both is that both of them can allow any company signing up with them to make developer accounts in their team.

For example, a company who has account with either azure or aws, can create developer accounts. These developer accounts will be given access keys and secrets keys to use in any application which wants to get data from them.

Person holding developer account must be part of company's team. Or in other words, admin decides who will be the developer in the team. This developer will be given access keys to get data from azure.

Azure don't give out the data to any third person until that person is part of the team and has his role defined in Identity and Access Management Tool.

It is different that how facebook or twitter provider work. They don't ask the user to make the application part of your account if you want facebook to send data to that application.

Azure want administrator to define the developer account and allow them access to products or put them in any groups.

http://azure.microsoft.com/en-in/documentation/articles/api-management-howto-create-or-invite-developers/

http://azure.microsoft.com/en-in/documentation/articles/api-management-key-concepts/

http://docs.aws.amazon.com/IAM/latest/UserGuide/IAM_Introduction.html

**Comment by jekram** [comment]
Here is the billing info on Azure:

http://azure.microsoft.com/en-us/documentation/articles/azure-billing-understand-your-bill/

**Comment by jekram** [comment]
Additional info on Azure:

a.	Guide: 
https://automaticbillingspec.blob.core.windows.net/spec/MicrosoftAzure–EABilling&UsageAPI.docx 

b.	Tech Spec: https://automaticbillingspec.blob.core.windows.net/spec/WAEP%20Functional%20Design%20-%20Automated%20Billing%20Access%20API%20Tech%20Spec.docx 

c.	Solution: https://automaticbillingspec.blob.core.windows.net/spec/UsageDownloadRestfulSampleClient.zip

These are only available for EA (large customers).

**Comment by jekram** [comment]
Thanks. The research has answered the question.
