### ISSUE TITLE
Define billing access for GitHub

### ISSUE THREAD

**Issue by jekram** [Cloudkibo/ice#8]
Waiting for a link from sojharo

**Comment by sojharo** [comment]
Salaam,

Internet was disconnecting frequently last night. Here are the links:

Informtion about libraries which are given by Github.

https://developer.github.com/libraries/

Documentation on API

https://developer.github.com/v3/

Development Guide

https://developer.github.com/guides/

And Developer Home Page

https://developer.github.com/

On Fri, May 22, 2015 at 5:20 AM, Cloudkibo <notifications@github.com> wrote:

> Waiting for a link from sojharo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Cloudkibo/ice/issues/8>.
>



-- 
Regards,

Sojharo

**Comment by jekram** [comment]
Thanjks

**Comment by jekram** [comment]
I am going to close this for now.
